### ISSUE TITLE
missing requests in requirements.txt

### ISSUE THREAD

**Issue by Pepepy** [JoelGMSec/LeakSearch#2]
It would be convenient to add requests to the requirements.txt, it is necessary to start the application and if the system is clean and does not have it installed it will give an error.

Otherwise, great work, thank you very much.

**Comment by sultanovich** [comment]
Hi team,

I have created a [PR](https://github.com/JoelGMSec/LeakSearch/pull/3) to resolve this issue, if you think it is appropriate, you can apply it.

**Comment by JoelGMSec** [comment]
Solved, thanks @sultanovich :)
