### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by whoot** [JoelGMSec/LeakSearch#4]
Hey, thanks for providing this tool and service.
However, I have the following issues.

## Number parameter not working as intended
Despite having set the N parameter, the tool just prints the first 20 records (note that 1914 records were found)
![grafik](https://github.com/JoelGMSec/LeakSearch/assets/8066322/1d42fa18-50e8-4148-840b-0efd6ee3ec3c)

EDIT: Looking into the code it seems that the number parameter is only used for truncating the output and that the API has a hardcoded limit of 20 records. This means that whenever there are more than 20 records, you only will be able to fetch the first 20 records. Anything beyond is not accessible at all - except there is something like an undocumented *offset* parameter?

## False-positive records
It seems that it is not possible to search for specific domains or full entries.
Example: searching for "test@test.com" results in 10.000 entries which do also contain other stuff.

![grafik](https://github.com/JoelGMSec/LeakSearch/assets/8066322/6d957b8d-865b-42c8-af5c-50259b1dbc14)

Also I noticed, that anything which contains a minus will result in false-positive records.
Example: Trying to get a list for the domain "@fake-box.com" gives me 10.000 records, which contain "_fake-box.com_" or either "_fake_" or "_box_".
![grafik](https://github.com/JoelGMSec/LeakSearch/assets/8066322/07059b41-6e48-42b8-be85-b9b65d7df371)

**Comment by JoelGMSec** [comment]
Hello!

Answering your questions:

The -n parameter works perfectly, it's just that ProxyNova (which is a third party, over which I have no control) has a limitation and only shows the first 20 results in all cases.

I have tried several times to find out if there is some undocumented parameter to get the next 20 (or more than 20) without success.

As for false positives and mixed results, more of the same. I do not own that service and cannot control or modify its contents. I have only created a client to perform these searches in the most comfortable way possible :)

I hope I have solved your doubts, thanks for using my tools.


Regards!

**Comment by whoot** [comment]
Ohh, I see! I thought you were also the one running ProxyNova, lol.
In this case I completely understand that there is nothing you can do.

**Comment by Oluwa-yemi** [comment]
> Hello!
> 
> Answering your questions:
> 
> The -n parameter works perfectly, it's just that ProxyNova (which is a third party, over which I have no control) has a limitation and only shows the first 20 results in all cases.
> 
> I have tried several times to find out if there is some undocumented parameter to get the next 20 (or more than 20) without success.
> 
> As for false positives and mixed results, more of the same. I do not own that service and cannot control or modify its contents. I have only created a client to perform these searches in the most comfortable way possible :)
> 
> I hope I have solved your doubts, thanks for using my tools.
> 
> Regards!



> Hello!
> 
> Answering your questions:
> 
> The -n parameter works perfectly, it's just that ProxyNova (which is a third party, over which I have no control) has a limitation and only shows the first 20 results in all cases.
> 
> I have tried several times to find out if there is some undocumented parameter to get the next 20 (or more than 20) without success.
> 
> As for false positives and mixed results, more of the same. I do not own that service and cannot control or modify its contents. I have only created a client to perform these searches in the most comfortable way possible :)
> 
> I hope I have solved your doubts, thanks for using my tools.
> 
> Regards!

Perhaps it would be better if you hosted the database yourself? As ProxyNova's is no longer working as of right now hence the project is no useful anymore. Unless you, as i said before, host the database.
